version: "3.7"

services:
  proxy:
    container_name: proxy
    image: alebabai/ssh-proxy:1.1.0
    environment:
      ADDRESSES: |-
        core:80
        authorization:80
    networks: 
      - internal
    volumes:
      - ./tmp:/tmp/ssh-proxy
